config/routes.rb
Rails.application.routes.draw do

  scope "(:locale)", locale: /hu|en/ do
    devise_for :users

    authenticated :user do
      root to: 'home#index'
      resources :users, only: [:show, :edit, :update]
      resources :posts, only: [:new, :create, :show, :destroy]
      get 'search' => 'search#index'
    end

    devise_scope :user do
      root to: 'devise/sessions#new'
    end

  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/hash_tag.rb
class HashTag < ApplicationRecord
  has_many :post_hash_tags
  has_many :posts, through: :post_hash_tags
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_one_attached :image

  has_many :post_hash_tags
  has_many :hash_tags, through: :post_hash_tags

  def extract_name_hash_tags
    description.to_s.scan(/#\w+/).map{|name| name.gsub("#", "")}
  end

  after_commit :create_hash_tags, on: :create

  def create_hash_tags
    extract_name_hash_tags.each do |name|
      hash_tags.create(name: name)
    end
  end

  validate :image_presence
  def image_presence
    errors.add(:image, "can't be blank") unless image.attached?
  end

end

app/models/post_hash_tag.rb
class PostHashTag < ApplicationRecord
  belongs_to :post
  belongs_to :hash_tag
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy

  has_one_attached :avatar

  validates :email, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  layout :layout_by_resource


  before_action :set_locale
  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
  end

  def default_url_options
    { locale: I18n.locale }
  end

  private
  def extract_locale_from_accept_language_header
    request.env['HTTP_ACCEPT_LANGUAGE'].scan(/^[a-z]{2}/).first
  end

  def layout_by_resource
    if devise_controller?
      "devise"
    else
      "application"
    end
  end

  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:username, :email, :password)}

    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:username, :email, :password, :current_password)}
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @posts = Post.order(created_at: :desc).page(params[:page]).per(5)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def create
    Post.create(post_params)
    redirect_to root_path
  end

  def show
    @post = Post.find(params[:id])
  end

  def destroy
    @post = current_user.posts.find(params[:id])
    @post.destroy
    redirect_to user_path(current_user)
  end

  private
  def post_params
    params.require(:post).permit(:description, :image, :user_id)
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
    if params[:query].start_with?('#')
      query  = params[:query].gsub('#', '')
      @posts = Post.joins(:hash_tags).where(hash_tags: {name:    query})
    else
      @posts = Post.where("description like ?", "%#{params[:query]}%")
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user  = User.find(params[:id])
    if (@user.id == current_user.id)
    {

    }
    end
    @posts = @user.posts.order(created_at: :desc)
  end

  def edit
    @user = current_user
  end

  def update
    current_user.update(user_params)
    redirect_to current_user
  end

  def profile

  end


  private

  def user_params
    params.require(:user).permit(:username, :name, :website, :bio, :email, :phone, :gender, :avatar)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/_post.html.erb
<section class="post">
  <%=link_to post_path(post) do %>
    <%= image_tag(post.image, class: 'main-image') %>
  <% end %>
  <div class="user">
    <div class="avatar">
      <% if post.user.avatar.attached? %>
        <%= link_to user_path(post.user) do %>
          <%= image_tag post.user.avatar %>
        <% end %>
      <% end %>
    </div>
    <%= link_to post.user.username, user_path(post.user), class: 'username' %>
  </div>
  <div class="description">
    <%= render partial: "posts/description", locals: {post: post} %>
  </div>
</section>

app/views/home/_upload_form.html.erb
<%= form_for Post.new do |f| %>
  <div class="form-group">
    <%= f.text_field :description %>
  </div>
  <div class="form-group">
    <%= f.file_field :image %>
  </div>
  <div class="form-group">
    <%= f.text_field :user_id, value: current_user.id, class: 'd-none' %>
  </div>
  <br>
  <div class="text-center">
    <%= f.submit t('post_form.upload_button'), class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/home/index.html.erb
<div class="homepage">
  <div class='form-upload'>
    <%= render 'upload_form' %>
  </div>

  <div class="posts">
    <% @posts.each do |post| %>
      <%= render partial: 'post', locals: { post: post } %>
    <% end %>
    <%= paginate @posts %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= Rails.configuration.site_name %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <!--Navigation Bar-->
  <nav class="navbar navbar-light d-flex fixed-top">
    <div class="container">
      <div class="logo">
        <a class="navbar-brand text-uppercase font-weight-bold" href="<%= root_url %>">
          <%= Rails.configuration.site_name %>
        </a>
      </div>
      <div class="m-auto">
        <%= form_with url: search_path, method: :get, local: true, class: 'form-inline search-form' do |form| %>
          <%= form.text_field :query, value: params[:query], class: 'form-control mr-sm-2', placeholder: t('search.placeholder') %>
        <% end %>
      </div>
      <div class="user-section">
          <a href="<%= user_path(current_user)%>">
            <!--<%= current_user.username %>-->
            <i class="fa fa-user"></i>
          </a>
      </div>
    </div>
  </nav>

  <!--Main content-->
  <main class="container">
    <% if notice %>
    <div class="alert alert-success" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
      <%= notice %>
    </div>
      <% end %>
    <% if alert %>
    <div class="alert alert-danger" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
      <%= alert %>
    </div>
      <% end %>
    <%= yield %>
  </main>

  <!--Footer-->
  <footer class="container footer">
    <p class="text-center">
      <% if I18n.locale == I18n.default_locale %>
        <%= link_to "English", { :locale=>'en' } %>

      <% else %>
        <%= link_to "Magyar", { :locale=>'hu' } %>

      <%end%>
    </p>
    <p class="text-center">&copy; <%= Date.today.year %> <%= Rails.configuration.site_name %></p>
  </footer>
  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Kotprog</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
<!--Main content-->
<main class="container h-full">
  <% if notice %>
    <div class="alert alert-success" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
      <%= notice %>
    </div>
  <% end %>
  <% if alert %>
    <div class="alert alert-danger" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
      <%= alert %>
    </div>
  <% end %>
  <div class="row justify-content-center">
    <div class="col">
        <h1 style="margin-bottom: 50px" class="text-center text-uppercase font-weight-bold"><%= Rails.configuration.site_name %></h1>
      <%= yield %>
    </div>
  </div>

</main>

<!--Footer-->
<footer class="container footer">
  <p class="text-center">
    <% if I18n.locale == I18n.default_locale %>
      <%= link_to "English", { :locale=>'en' } %>

    <% else %>
      <%= link_to "Magyar", { :locale=>'hu' } %>

    <%end%>
  </p>
  <p class="text-center">&copy; <%= Date.today.year %> <%= Rails.configuration.site_name %></p>
</footer>
</body>
</html>

app/views/posts/_description.html.erb
<% post.description.to_s.split(' ').each do |word| %>
  <% if word.start_with?('#') %>
    <%= link_to word, search_path(query: word) %>
  <%else %>
    <%= word %>
  <%end %>
<% end %>

app/views/posts/show.html.erb
<%= link_to t('post.back'), :back , class: ''%>
<div class="post-show row">
  <div class="col-md-8">
    <%=image_tag @post.image, class: 'image' %>
  </div>
  <div class="col-md-4">
    <div class="user">
      <div class="avatar">
        <% if @post.user.avatar.attached? %>
          <%= link_to user_path(@post.user) do %>
            <%= image_tag @post.user.avatar %>
          <% end %>
        <% end %>
      </div>
      <%= link_to @post.user.username, user_path(@post.user), class: 'username' %>
    </div>
    <div class="description">
      <% @post.description.to_s.split(' ').each do |word| %>
        <% if word.start_with?('#') %>
          <%= link_to word, search_path(query: word) %>
        <%else %>
          <%= word %>
        <%end %>
      <% end %>
    </div>
    <div class="delete">
      <% if current_user.posts.exists?(@post.id) %>
        <%= link_to t('post.delete'), post_path(@post), method: :delete, data: { confirm: t('post.delete_confirm') } %>
      <% end %>
    </div>
  </div>
</div>

app/views/search/index.html.erb
<div class="search-page">
  <% if @posts.exists? %>
    <h1>Top Posts</h1>
  <% else %>
    <h1>Oop! No matching posts ...</h1>
  <% end %>
  <div class="user-images">
    <% @posts.each do |post|%>
      <div class="wrapper">
        <%=link_to post_path(post) do %>
          <%=image_tag post.image %>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/edit.html.erb
<div class="user-edit-page">
  <div class="actions">
    <div class="nav flex-column nav-pills" role="tablist" aria-orientation="vertical">
      <a class="nav-link active" data-toggle="pill" href="#v-pills-home" role="tab" aria-selected="true"><%= t('profile_edit.menu.edit_profile') %></a>
      <a class="nav-link" data-toggle="pill"><%= t('profile_edit.menu.change_password') %></a>
      <%= link_to t('profile_edit.menu.logout'), destroy_user_session_path, method: :delete, class: "nav-link" %>
    </div>
  </div>
  <div class="details tab-content">
    <div class="tab-pane fade show active" id="v-pills-home" role="tabpanel" aria-labelledby="v-pills-home-tab">
      <%= form_with model: current_user, local: true, html: {class: "form-horizontal form-edit-user"} do |f| %>
        <div class="form-group row">
          <div class="col-sm-3 col-form-label">
            <% if current_user.avatar.attached? %>
              <%= image_tag current_user.avatar, class: 'avatar' %>
            <%end %>
          </div>
          <div class="col-sm-9">
            <p class="username"><%=current_user.username %></p>
          </div>
        </div>
        <div class="form-group row">
          <%= f.label :avatar, class: 'col-sm-3 col-form-label' %>
          <div class="col-sm-9">
            <%= f.file_field :avatar, class: 'form-control' %>
          </div>
        </div>
        <div class="form-group row">
          <%= f.label :name, class: 'col-sm-3 col-form-label' %>
          <div class="col-sm-9">
            <%= f.text_field :name, class: 'form-control' %>
          </div>
        </div>
        <div class="form-group row">
          <%= f.label :username, class: 'col-sm-3 col-form-label' %>
          <div class="col-sm-9">
            <%= f.text_field :username, class: 'form-control' %>
          </div>
        </div>
        <div class="form-group row">
          <%= f.label :website, class: 'col-sm-3 col-form-label' %>
          <div class="col-sm-9">
            <%= f.text_field :website, class: 'form-control' %>
          </div>
        </div>
        <div class="form-group row">
          <%= f.label :bio, class: 'col-sm-3 col-form-label' %>
          <div class="col-sm-9">
            <%= f.text_area :bio, class: 'form-control' %>
          </div>
        </div>
        <div class="form-group row">
          <%= f.label :email, class: 'col-sm-3 col-form-label' %>
          <div class="col-sm-9">
            <%= f.text_field :email, class: 'form-control' %>
          </div>
        </div>
        <div class="form-group row">
          <%= f.label :phone, class: 'col-sm-3 col-form-label' %>
          <div class="col-sm-9">
            <%= f.text_field :phone, class: 'form-control' %>
          </div>
        </div>
        <div class="form-group row">
          <%= f.label :gender, class: 'col-sm-3 col-form-label' %>
          <div class="col-sm-9">
            <%= f.text_field :gender, class: 'form-control' %>
          </div>
        </div>
        <div class="form-group row">
          <div class="col-sm-3">
          </div>
          <div class="col-sm-9">
            <%= f.submit t('helpers.label.user.submit'), class: 'btn btn-primary' %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="user-profile">
  <div class="profile row">
    <div class="col-md-4 avatar">
      <div class="wrapper">
        <% if @user.avatar.attached? %>
          <%= image_tag @user.avatar %>
        <%end %>
      </div>
    </div>

    <div class="col-md-8 basic-info">
      <div class="user-wrapper">
        <h2 class="username"><%= @user.username %></h2>
        <% if current_user.id == @user.id%>
        <a class="edit-profile" href="<%= edit_user_path(current_user) %>">
          <button><%= t('profile.edit_profile') %></button>
        </a>
          <% end %>
      </div>
      <ul class="posts">
        <li><span><%= @posts.count %></span> <%= t('profile.post') %></li>
        <li><span>195</span> <%= t('profile.followers') %></li>
        <li><span>345</span> <%= t('profile.following') %></li>
      </ul>
      <h2 class="name"><%= @user.name %></h2>
      <a class="website"><%= @user.website %></a>
    </div>
  </div>
</div>

<div class="user-images">
  <% @posts.each do |post|%>
    <div class="wrapper">
      <%=link_to post_path(post) do %>
        <%=image_tag post.image %>
      <% end %>
    </div>
  <% end %>
</div>